In [14]:
import numpy as np
arr = np.array([2,4,6,8])
arr/5

array([0.4, 0.8, 1.2, 1.6])

In [23]:
import numpy as np
list = np.array([1,2,3,4,5,6,7,8,9,10])

list%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [38]:
cars = ['dsd','sdsads','dgdfd']
print(cars[2])

dgdfd


In [42]:
cars = ['BMW','Avanza','Toyota']
cars[0] = 'Alphard'
x = len(cars)
print(x)

3


In [47]:
cars = ['Ford','Volvo','BMW']
cars.append("Honda")
for x in cars:
  print(x)

Ford
Volvo
BMW
Honda


In [87]:
student = ['Pasca','Riri','Neva','Najla','Caca']
other_student = ['Dzikri','Vicky','Aripin']
x = student.copy()
y = student.count('Riri')
z = student.extend(other_student)
print(x)
print(y)
print(student)

['Pasca', 'Riri', 'Neva', 'Najla', 'Caca']
1
['Pasca', 'Riri', 'Neva', 'Najla', 'Caca', 'Dzikri', 'Vicky', 'Aripin']


In [84]:
import numpy as np 
list = [1,2,3,4]

sample_numpy = np.array(list)

print('list in python',list)
print('numpy array from python',sample_numpy)

list in python [1, 2, 3, 4]
numpy array from python [1 2 3 4]


In [98]:
import numpy as np

names = np.array(["Reem" , "Salah" , "Haya" , "Maryam" , "Fatema"])

names[2] = "Omar"

print(names)

['Reem' 'Salah' 'Omar' 'Maryam' 'Fatema']


In [92]:
x = np.array([1,2,3])
x
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [99]:
import array as myarr

no = myarr.array('b', [10, 4, 5, 5, 7])

del no[4]

print(no)

array('b', [10, 4, 5, 5])
